function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action.pressed then
		if gui.pick_node(gui.get_node("cards_button"), action.x, action.y) then
			msg.post("#gameloader", "play_cards")
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
